http_port 3128

acl lab_containers src 172.23.0.0/24
acl safe_ports port 80 443
acl ssl_ports port 443
acl CONNECT method CONNECT

http_access deny !safe_ports
http_access deny CONNECT !ssl_ports
http_access allow lab_containers
http_access deny all

cache deny all
access_log none
